Upstreamed changes from deploy-VFIO.

diff --git a/bin/bashlib-files b/bin/bashlib-files
--- a/bin/bashlib-files
+++ b/bin/bashlib-files
@@ -15,8 +15,8 @@
 
 # <code>
     # <summary> Check if two given files are the same. If true, pass. </summary>
-    # <parameter name=1> string: the file </parameter>
-    # <parameter name=2> string: the other file </parameter>
+    # <parameter name="1"> string: the file </parameter>
+    # <parameter name="2"> string: the other file </parameter>
     function AreEqualFiles
     {
         IsFile $2 || return $?
@@ -26,7 +26,7 @@
     }
 
     # <summary> Create latest backup of given file. </summary>
-    # <parameter name=1> string: the file </parameter>
+    # <parameter name="1"> string: the file </parameter>
     function BackupFile
     {
         function BackupFile_Main
@@ -36,7 +36,7 @@
             # <params>
             local str_dir=$( dirname $1 )
             local str_suffix=".old"
-            declare -a arr_dir=( $( eval 'ls -t '"${str_dir}"' | grep '$1' | grep -i '"${str_suffix}"' | uniq' ) )
+            declare -a arr_dir=( $( eval 'ls -t '"${str_dir}"' | grep '${1}' | grep -i '"${str_suffix}"' | uniq' ) )
             # </params>
 
             # <remarks> If none exist, create backup. </remarks>
@@ -70,14 +70,14 @@
     }
 
     # <summary> Create a directory. </summary>
-    # <param name=1> string: the directory </param>
+    # <param name="1"> string: the directory </param>
     function CreateDir
     {
         IsString $1 || return $?
         IsDir $1 &> /dev/null && return 0
 
         if ! mkdir -p $1 &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not create directory '$1'."
+            echo -e "${var_prefix_fail} Could not create directory '${1}'."
             return 1
         fi
 
@@ -85,14 +85,14 @@
     }
 
     # <summary> Create a file. </summary>
-    # <param name=1> string: the file </param>
+    # <param name="1"> string: the file </param>
     function CreateFile
     {
         IsString $1 || return $?
         IsFile $1 &> /dev/null && return 0
 
         if ! touch $1 &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not create file '$1'."
+            echo -e "${var_prefix_fail} Could not create file '${1}'."
             return 1
         fi
 
@@ -100,14 +100,14 @@
     }
 
     # <summary> Delete a directory. </summary>
-    # <param name=1> string: the file </param>
+    # <param name="1"> string: the file </param>
     function DeleteDir
     {
         IsString $1 || return $?
         IsDir $1 &> /dev/null || return 1
 
         if ! rm -r '"$1"' &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not delete directory '$1'."
+            echo -e "${var_prefix_fail} Could not delete directory '${1}'."
             return 1
         fi
 
@@ -115,14 +115,14 @@
     }
 
     # <summary> Delete a file. </summary>
-    # <param name=1> string: the file </param>
+    # <param name="1"> string: the file </param>
     function DeleteFile
     {
         IsString $1 || return $?
         IsFile $1 &> /dev/null || return 1
 
         if ! rm '"$1"' &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not delete file '$1'."
+            echo -e "${var_prefix_fail} Could not delete file '${1}'."
             return 1
         fi
 
@@ -130,8 +130,8 @@
     }
 
     # <summary> Find line in file. </summary>
-    # <param name=1> string: the file </param>
-    # <param name=2> string: the line </param>
+    # <param name="1"> string: the file </param>
+    # <param name="2"> string: the line </param>
     function FindLineInFile
     {
         IsString $2 || return $?
@@ -141,13 +141,13 @@
     }
 
     # <summary> Check if the directory exists. If true, pass. </summary>
-    # <param name=1> string: the directory name </param>
+    # <param name="1"> string: the directory name </param>
     function IsDir
     {
         IsString $1 || return $?
 
         if [[ ! -d $1 ]]; then
-            echo -e "${var_prefix_error} File '$1' is not a directory."
+            echo -e "${var_prefix_error} File '${1}' is not a directory."
             return $int_code_dir_is_null
         fi
 
@@ -155,13 +155,13 @@
     }
 
     # <summary> Check if the file exists. If true, pass. </summary>
-    # <param name=1> string: the file name </param>
+    # <param name="1"> string: the file name </param>
     function IsFile
     {
         IsString $1 || return $?
 
         if [[ ! -e $1 ]]; then
-            echo -e "${var_prefix_error} '$1' is not a file."
+            echo -e "${var_prefix_error} '${1}' is not a file."
             return $int_code_dir_is_null
         fi
 
@@ -169,8 +169,8 @@
     }
 
     # <summary> Check if first file is newer than second file. If true, pass. </summary>
-    # <parameter name=1> string: the file </parameter>
-    # <parameter name=2> string: the other file </parameter>
+    # <parameter name="1"> string: the file </parameter>
+    # <parameter name="2"> string: the other file </parameter>
     function IsFileNewer
     {
         IsFile $2 || return $?
@@ -180,8 +180,8 @@
     }
 
     # <summary> Check if first file is older than second file. If true, pass. </summary>
-    # <parameter name=1> string: the file </parameter>
-    # <parameter name=2> string: the other file </parameter>
+    # <parameter name="1"> string: the file </parameter>
+    # <parameter name="2"> string: the other file </parameter>
     function IsFileOlder
     {
         IsFile $2 || return $?
@@ -192,13 +192,13 @@
 
 
     # <summary> Check if the file is executable. If true, pass. </summary>
-    # <param name=1> string: the file name </param>
+    # <param name="1"> string: the file name </param>
     function IsFileExecutable
     {
         IsFile $1 || return $?
 
         if [[ ! -x $1 ]]; then
-            echo -e "${var_prefix_error} File '$1' is not executable."
+            echo -e "${var_prefix_error} File '${1}' is not executable."
             return $int_code_file_is_not_executable
         fi
 
@@ -206,13 +206,13 @@
     }
 
     # <summary> Check if the file is readable. If true, pass. </summary>
-    # <param name=1> string: the file name </param>
+    # <param name="1"> string: the file name </param>
     function IsFileReadable
     {
         IsFile $1 || return $?
 
         if [[ ! -r $1 ]]; then
-            echo -e "${var_prefix_error} File '$1' is not readable."
+            echo -e "${var_prefix_error} File '${1}' is not readable."
             return $int_code_file_is_not_readable
         fi
 
@@ -220,13 +220,13 @@
     }
 
     # <summary> Check if the file is writable. If true, pass. </summary>
-    # <param name=1> string: the file name </param>
+    # <param name="1"> string: the file name </param>
     function IsFileWritable
     {
         IsFile $1 || return $?
 
         if [[ ! -w $1 ]]; then
-            echo -e "${var_prefix_error} File '$1' is not writable."
+            echo -e "${var_prefix_error} File '${1}' is not writable."
             return $int_code_file_is_not_writable
         fi
 
@@ -234,8 +234,8 @@
     }
 
     # <summary> Overwrite output to a file. </summary>
-    # <paramref name=1> string: the name of the array </paramref>
-    # <param name=2> string: the name of the file </param>
+    # <paramref name="1"> string: the name of the array </paramref>
+    # <param name="2"> string: the name of the file </param>
     function OverwriteFile
     {
         IsArray $1 || return $?
@@ -246,7 +246,7 @@
     }
 
     # <summary> Output a file. </summary>
-    # <param name=1> string: the file </param>
+    # <param name="1"> string: the file </param>
     function PrintFile
     {
         IsFile $1 || return $?
@@ -256,14 +256,14 @@
         declare -a arr_print_file=( )
         # </params>
 
-        ReadFile arr_print_file $1 || return $?
-        PrintArray arr_print_file
+        ReadFile "arr_print_file" $1 || return $?
+        PrintArray "arr_print_file"
         return $?
     }
 
     # <summary> Read input from a file. Declare inherited params before calling this function. </summary>
-    # <paramref name=1> string: the name of the array </paramref>
-    # <param name=2> string: the name of the file </param>
+    # <paramref name="1"> string: the name of the array </paramref>
+    # <param name="2"> string: the name of the file </param>
     function ReadFile
     {
         IsFile $2 || return $?
@@ -274,7 +274,7 @@
         # </params>
 
         if ! mapfile -t < <( cat $2 ) || ! IsArray "MAPFILE" &> /dev/null; then
-            echo -e "${var_prefix_fail} Could not read from file '$2'."
+            echo -e "${var_prefix_fail} Could not read from file '${2}'."
             return 1
         fi
 
@@ -283,9 +283,9 @@
     }
 
     # <summary> Replace line in an file. </summary>
-    # <param name=1> string: the name of the file </param>
-    # <param name=2> string: the line </param>
-    # <param name=3> string: the new line </param>
+    # <param name="1"> string: the name of the file </param>
+    # <param name="2"> string: the line </param>
+    # <param name="3"> string: the new line </param>
     function ReplaceLineInFile
     {
         IsString $3 || return $?
@@ -294,13 +294,13 @@
         declare -a arr_replace_file=()
         # </params>
 
-        ReadFile arr_replace_file $1 || return $?
-        ReplaceLineInArray arr_replace_file $2 $3 || return $?
+        ReadFile "arr_replace_file" $1 || return $?
+        ReplaceLineInArray "arr_replace_file" $2 $3 || return $?
         return 0
     }
 
     # <summary> Restore latest valid backup of given file. </summary>
-    # <parameter name=1> string: the name of the file </param>
+    # <parameter name="1"> string: the name of the file </param>
     function RestoreFile
     {
         function RestoreFile_Main
@@ -310,7 +310,7 @@
             # <params>
             local str_dir=$( dirname $1 )
             local str_suffix=".old"
-            declare -a arr_dir=( $( eval 'ls -t '"${str_dir}"' | grep '$1' | grep -i '"${str_suffix}"' | uniq' ) )
+            declare -a arr_dir=( $( eval 'ls -t '"${str_dir}"' | grep '${1}' | grep -i '"${str_suffix}"' | uniq' ) )
             # </params>
 
             # <remarks> If none exist, create backup. </remarks>
@@ -334,15 +334,15 @@
     }
 
     # <summary> Write output to a file. Declare inherited params before calling this function. </summary>
-    # <paramref name=1> string: the name of the array </paramref>
-    # <param name=2> string: the name of the file </param>
+    # <paramref name="1"> string: the name of the array </paramref>
+    # <param name="2"> string: the name of the file </param>
     function WriteFile
     {
         IsFile $2 || return $?
         IsArray $1 || return $?
 
-        if ! printf "%s\n" "${'$1'[@]}" >> $2; then
-            echo -e "${var_prefix_fail} Could not write to file '$1'."
+        if ! printf "%s\n" "${'${1}'[@]}" >> $2; then
+            echo -e "${var_prefix_fail} Could not write to file '${1}'."
             return 1
         fi
 
