Upstreamed changes from deploy-VFIO.

diff --git a/bin/bashlib-dev b/bin/bashlib-dev
--- a/bin/bashlib-dev
+++ b/bin/bashlib-dev
@@ -23,37 +23,36 @@
 
         # <params>
         local str_commands_to_execute=""
-        local str_output_invalid_package_manager="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
         local str_output_invalid_package="${var_prefix_fail}: Package(s) '${str_package_manager}' was/were not found."
         # </params>
 
         case "${str_package_manager}" in
             "apt" )
-                str_commands_to_execute="apt list ${1}"
+                str_commands_to_execute="apt list $1"
                 ;;
 
             "dnf" )
-                str_commands_to_execute="dnf search ${1}"
+                str_commands_to_execute="dnf search $1"
                 ;;
 
             "pacman" )
-                str_commands_to_execute="pacman -Ss ${1}"
+                str_commands_to_execute="pacman -Ss $1"
                 ;;
 
             "gentoo" )
-                str_commands_to_execute="emerge --search ${1}"
+                str_commands_to_execute="emerge --search $1"
                 ;;
 
             "urpmi" )
-                str_commands_to_execute="urpmq ${1}"
+                str_commands_to_execute="urpmq $1"
                 ;;
 
             "yum" )
-                str_commands_to_execute="yum search ${1}"
+                str_commands_to_execute="yum search $1"
                 ;;
 
             "zypper" )
-                str_commands_to_execute="zypper se ${1}"
+                str_commands_to_execute="zypper se $1"
                 ;;
 
             * )
@@ -233,33 +232,6 @@
         return 0
     }
 
-    # <summary> Distro-agnostic, check if package is installed. </summary>
-    # <param name=$1> string: the software package(s) </param>
-    # <param name="${str_package_manager}"> string: the package manager </param>
-    function IsInstalledPackage
-    {
-        IsString "${str_package_manager}" || return $?
-        IsString $1 || return $?
-
-        # <params>
-        local str_fail="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
-        # </params>
-
-        # <remarks> Check if package is not installed </remarks>
-        case "${str_package_manager}" in
-            "apt" )
-                dpkg -s $1 &> /dev/null || InstallPackage $1 || return $?
-                ;;
-
-            * )
-                echo -e "${str_fail}"
-                return 1
-                ;;
-        esac
-
-        return 0
-    }
-
     # <summary> Distro-agnostic, Install a software package. </summary>
     # <param name=$1> string: the software package(s) </param>
     # <param name=$2> boolean: true/false do/don't reinstall software package and configuration files (if possible) </param>
@@ -273,7 +245,6 @@
         local bool_option_reinstall=false
         local str_commands_to_execute=""
         local str_output="Installing software packages..."
-        local str_fail="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
         # </params>
 
         IsBool $2 &> /dev/null && bool_option_reinstall=true
@@ -282,35 +253,35 @@
         case "${str_package_manager}" in
             "apt" )
                 local str_option="--reinstall -o Dpkg::Options::=--force-confmiss"
-                str_commands_to_execute="apt update && apt full-upgrade -y && apt install ${str_option} -y ${1}"
+                str_commands_to_execute="apt update && apt full-upgrade -y && apt install ${str_option} -y $1"
                 ;;
 
             "dnf" )
-                str_commands_to_execute="dnf upgrade && dnf install ${1}"
+                str_commands_to_execute="dnf upgrade && dnf install $1"
                 ;;
 
             "pacman" )
-                str_commands_to_execute="pacman -Syu && pacman -S ${1}"
+                str_commands_to_execute="pacman -Syu && pacman -S $1"
                 ;;
 
             "gentoo" )
-                str_commands_to_execute="emerge -u @world && emerge ${1}"
+                str_commands_to_execute="emerge -u @world && emerge $1"
                 ;;
 
             "urpmi" )
-                str_commands_to_execute="urpmi --auto-update && urpmi ${1}"
+                str_commands_to_execute="urpmi --auto-update && urpmi $1"
                 ;;
 
             "yum" )
-                str_commands_to_execute="yum update && yum install ${1}"
+                str_commands_to_execute="yum update && yum install $1"
                 ;;
 
             "zypper" )
-                str_commands_to_execute="zypper refresh && zypper in ${1}"
+                str_commands_to_execute="zypper refresh && zypper in $1"
                 ;;
 
             * )
-                echo -e "${str_fail}"
+                echo -e "${str_output_invalid_package_manager}"
                 return 1
                 ;;
         esac
@@ -319,6 +290,42 @@
         eval "${str_commands_to_execute}" || ( return 1 )
         PrintPassOrFail "${str_output}"
         return $?
+    }
+
+    # <summary> Distro-agnostic, check if package is installed. </summary>
+    # <param name=$1> string: the software package(s) </param>
+    # <param name="${str_package_manager}"> string: the package manager </param>
+    function IsInstalledPackage
+    {
+        IsString "${str_package_manager}" || return $?
+        IsString $1 || return $?
+
+        # <params>
+        local var_get_command=""
+        # </params>
+
+        # <remarks> Check if package is not installed </remarks>
+        case "${str_package_manager}" in
+            "apt" )
+                var_get_command="dpkg -s $1" || return $?
+                ;;
+
+            * )
+                echo -e "${str_output_invalid_package_manager}"
+                return 1
+                ;;
+        esac
+
+        declare -i int_delim=1
+
+        while true; do
+            local str_package=$( echo $1 | cut -d ' ' -f $int_delim )
+            IsString $str_package &> /dev/null || return 0
+            eval "${var_get_command}" &> /dev/null || break
+            (( int_delim++ ))
+        done
+
+        return 1
     }
 
     # <summary> Update GetInternetStatus </summary>
@@ -339,41 +346,40 @@
         # <params>
         local str_commands_to_execute=""
         local str_output="Uninstalling software packages..."
-        local str_fail="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
         # </params>
 
         # <remarks> Uninstall selected packages </remarks>
         case "${str_package_manager}" in
             "apt" )
-                str_commands_to_execute="apt uninstall ${1}"
+                str_commands_to_execute="apt uninstall $1"
                 ;;
 
             "dnf" )
-                str_commands_to_execute="dnf remove ${1}"
+                str_commands_to_execute="dnf remove $1"
                 ;;
 
             "pacman" )
-                str_commands_to_execute="pacman -R ${1}"
+                str_commands_to_execute="pacman -R $1"
                 ;;
 
             "gentoo" )
-                str_commands_to_execute="emerge -Cv ${1}"
+                str_commands_to_execute="emerge -Cv $1"
                 ;;
 
             "urpmi" )
-                str_commands_to_execute="urpme ${1}"
+                str_commands_to_execute="urpme $1"
                 ;;
 
             "yum" )
-                str_commands_to_execute="yum remove ${1}"
+                str_commands_to_execute="yum remove $1"
                 ;;
 
             "zypper" )
-                str_commands_to_execute="zypper remove ${1}"
+                str_commands_to_execute="zypper remove $1"
                 ;;
 
             * )
-                echo -e "${str_fail}"
+                echo -e "${str_output_invalid_package_manager}"
                 return 1
                 ;;
         esac
@@ -390,23 +396,28 @@
     # <param name=$3> string: the username </param>
     function UpdateOrCloneGitRepo
     {
-        CreateDir "${1}${3}"
+        IsString $3 || return $?
+        IsString $2 || return $?
+        IsString $1 || return $?
+        CreateDir "$1$3"
 
         # <summary> Update existing GitHub repository. </summary>
-        if IsDir "${1}${2}" &> /dev/null; then
+        if IsDir "$1$2"; then
             local var_command="git pull"
-
-            cd "${1}${2}" && StopEvalAfterThriceFail $( eval "${var_command}" ) &> /dev/null
-            return $?
+            cd "$1$2"
+            eval "${var_command}" &> /dev/null || return 1
+            return 0
 
         # <summary> Clone new GitHub repository. </summary>
-        elif IsDir "${1}${3}" &> /dev/null; then
-            if ReadInput "Clone repo '${2}'?"; then
-                local var_command="git clone https://github.com/${2}"
-
-                cd "${1}${3}" && StopEvalAfterThriceFail $( eval "${var_command}" ) &> /dev/null
-                return $?
+        elif IsDir "$1$3"; then
+            if ReadInput "Clone repo '$2'?"; then
+                local var_command="git clone https://github.com/$2"
+                cd "$1$3"
+                eval "${var_command}" &> /dev/null || return 1
+                return 0
             fi
+
+            return 1
         else
             return 1
         fi
@@ -414,9 +425,12 @@
 # </code>
 
 # <params>
-declare -g bool_is_installed_systemd=false
-IsInstalledCommand "systemd" &> /dev/null && bool_is_installed_systemd=true
+    declare -g str_output_invalid_package_manager="${var_prefix_fail}: Command '${str_package_manager}' is not supported."
 
-declare -gl str_package_manager=""
-GetLinuxDistro &> /dev/null
+    # <summary> System validation </summary>
+    declare -g bool_is_installed_systemd=false
+    IsInstalledCommand "systemd" &> /dev/null && bool_is_installed_systemd=true
+
+    declare -gl str_package_manager=""
+    GetLinuxDistro &> /dev/null
 # </params>
diff --git a/bin/bashlib-misc b/bin/bashlib-misc
--- a/bin/bashlib-misc
+++ b/bin/bashlib-misc
@@ -16,13 +16,9 @@
 # <code>
     # <summary> Redirect current directory to shell script root directory. </summary>
     # <param name="${0}"> string: the shell script name </param>
-    function GoToScriptDir
+    function GetScriptDir
     {
-        # <params>
-        local str_dir=$( dirname "${0}" )
-        # </params>
-
-        cd "${str_dir}" || return 1
+        cd "${str_script_dir}" || return 1
         return 0
     }
 
@@ -33,7 +29,7 @@
     function PrintPassOrFail
     {
         SaveExitCode
-        IsString $1 &> /dev/null && echo -en "${1} "
+        IsString $1 &> /dev/null && echo -en "$1\t"
 
         case "${int_exit_code}" in
             0 )
@@ -80,23 +76,33 @@
         # </params>
     }
 
+    # <summary> Set script directory. Call this function before calling Getter. </summary>
+    # <param name="${0}"> string: the shell script name </param>
+    function SetScriptDir
+    {
+        # <params>
+        str_script_dir=$( dirname $( pwd ) )
+        # </params>
+
+        IsString $str_script_dir || return 1
+        return 0
+    }
+
     # <summary> Attempt given command a given number of times before failure. </summary>
     # <param name=$1> string: the command to execute </param>
-    function StopEvalAfterThriceFail        # NEEDS WORK
+    function StopEvalAfterThriceFail
     {
         IsString $1 || return $?
 
-        # <params>
-        declare -ir int_min_count=1
-        declare -ir int_max_count=3
-        declare -ar arr_count=$( eval echo {$int_min_count..$int_max_count} )
-        local str_fail="${var_prefix_error} Execution of command failed."
-        # </params>
-
         for int_count in ${arr_count[@]}; do
-            eval $1 && return 0 || echo -e "${str_fail}"
+            eval $1 && return 0 || echo -e "${str_fail_command}"
         done
 
         return 1
     }
 # </code>
+
+# <params>
+    # <summary> Output statement </summary>
+    declare -g str_fail_command="${var_prefix_error} Execution of command failed."
+# </params>
