Upstreamed changes from deploy-VFIO.

diff --git a/bin/bashlib-misc b/bin/bashlib-misc
--- a/bin/bashlib-misc
+++ b/bin/bashlib-misc
@@ -15,49 +15,45 @@
 
 # <code>
     # <summary> Redirect current directory to shell script root directory. </summary>
-    # <param name="${0}"> string: the shell script name </param>
-    function GoToScriptDir
+    # <param name=0> string: the shell script name </param>
+    function GetScriptDir
     {
-        # <params>
-        local str_dir=$( dirname "${0}" )
-        # </params>
-
-        cd "${str_dir}" || return 1
+        cd $str_script_dir || return 1
         return 0
     }
 
     # <summary> Append Pass or Fail given exit code. </summary>
-    # <param name="${int_exit_code}"> the last exit code </param>
-    # <param name=$1> string: the output statement </param>
+    # <param name=int_exit_code> the last exit code </param>
+    # <param name=1> string: the output statement </param>
     # <returns> output statement </returns>
     function PrintPassOrFail
     {
         SaveExitCode
-        IsString $1 &> /dev/null && echo -en "${1} "
+        IsString $1 &> /dev/null && echo -en "${1}\t"
 
-        case "${int_exit_code}" in
+        case $int_exit_code in
             0 )
-                echo -e "${var_suffix_pass}"
+                echo -e $var_suffix_pass
                 ;;
 
-            "${int_code_partial_completion}" )
-                echo -e "${var_suffix_maybe}"
+            $int_code_partial_completion )
+                echo -e $var_suffix_maybe
                 ;;
 
-            "${int_code_skipped_operation}" )
-                echo -e "${var_suffix_skip}"
+            $int_code_skipped_operation )
+                echo -e $var_suffix_skip
                 ;;
 
             * )
-                echo -e "${var_suffix_fail}"
+                echo -e $var_suffix_fail
                 ;;
         esac
 
-        return "${int_exit_code}"
+        return $int_exit_code
     }
 
     # <summary> Parse exit code as boolean. If zero, return true. Else, return false. </summary>
-    # <param name=$?> int: the exit code </param>
+    # <param name=?> int: the exit code </param>
     # <returns> boolean </returns>
     function ParseExitCodeAsBool
     {
@@ -71,30 +67,33 @@
     }
 
     # <summary> Save last exit code. </summary>
-    # <param name=""${int_exit_code}""> the exit code </param>
+    # <param name=int_exit_code> the exit code </param>
     # <returns> void </returns>
     function SaveExitCode
     {
-        # <params>
         int_exit_code=$?
+    }
+
+    # <summary> Set script directory. Call this function before calling Getter. </summary>
+    # <param name=0> string: the shell script name </param>
+    function SetScriptDir
+    {
+        # <params>
+        str_script_dir=$( dirname $( pwd ) )
         # </params>
+
+        IsString $str_script_dir || return 1
+        return 0
     }
 
     # <summary> Attempt given command a given number of times before failure. </summary>
-    # <param name=$1> string: the command to execute </param>
-    function StopEvalAfterThriceFail        # NEEDS WORK
+    # <param name=1> string: the command to execute </param>
+    function StopEvalAfterThriceFail
     {
         IsString $1 || return $?
 
-        # <params>
-        declare -ir int_min_count=1
-        declare -ir int_max_count=3
-        declare -ar arr_count=$( eval echo {$int_min_count..$int_max_count} )
-        local str_fail="${var_prefix_error} Execution of command failed."
-        # </params>
-
         for int_count in ${arr_count[@]}; do
-            eval $1 && return 0 || echo -e "${str_fail}"
+            eval $1 && return 0 || echo -e "${var_prefix_error} Execution of command failed."
         done
 
         return 1
