Working on BackupFile.

diff --git a/bashlib-files b/bashlib-files
--- a/bashlib-files
+++ b/bashlib-files
@@ -31,74 +31,76 @@
         return 0
     }
 
-    # # TODO: needs work!
-    # # <summary> Create latest backup of given file (do not exceed given maximum count). </summary>
-    # # <parameter name=$1> string: the file </parameter>
-    # # <returns> exit code </returns>
-    # function BackupFile
-    # {
-    #     function BackupFile_Main
-    #     {
-    #         # TODO: need to reverse pad out zeros, such that we can get the proper integer.
+    # TODO: needs work!
+    # <summary> Create latest backup of given file (do not exceed given maximum count). </summary>
+    # <parameter name=$1> string: the file </parameter>
+    # <returns> exit code </returns>
+    function BackupFile
+    {
+        function BackupFile_Main
+        {
+            funcion BackupFile_GetNum
+            {
+                IsString $1 || return $?
 
-    #         IsFile $1 || return $?
+                # <params>
+                declare -i int_index=$1
+                local readonly var_pad_zeros='$( printf %03d $int_index )'
+                # </params>
 
-    #         # <params>
-    #         declare -ir int_max_count=5
-    #         local readonly str_suffix=".old"
-    #         local readonly var_get_backups='ls '"${str_dir}"' | grep '$1' | grep -i '"${str_suffix}"' | uniq | sort -V'
-    #         local readonly var_pad_zeros='str_index=$( printf %03d "${int_index}" )'
-    #         declare -a arr_dir=( $( eval "${var_get_backups}" ) )
-    #         declare -i int_index=1
-    #         # </params>
+                # convert string of '008' to '8'
 
-    #         # <remarks> Get index of oldest backup file. </remarks>
-    #         local str_oldest_file="${arr_dir[0]}"
-    #         str_oldest_file="${str_oldest_file%%"${str_suffix}"*}"
-    #         str_index="${str_oldest_file##*0}"
-    #         IsNum "$str_index" && int_index="${str_index}" || int_index=1
-    #         eval "${var_pad_zeros}"
+                (( int_index++ ))
 
-    #         # <remarks> If none exist, create backup. </remarks>
-    #         if ! IsArray arr_dir; then
-    #             cp $1 "${1}.${str_index}${str_suffix}" || return 1
-    #         fi
+                if [[ "$int_index" -ge "${int_max_count}" ]]; then
+                    int_index=1
+                fi
 
-    #         # <remarks> If newest backup is same as file, exit. </remarks>
-    #         if AreEqualFiles $1 "${arr_dir[-1]}"; then
-    #             return 0
-    #         fi
+                eval "${var_pad_zeros}"
+            }
 
-    #         # <remarks> If amount of backups exceeds maximum, delete oldest backup. </remarks>
-    #         if [[ "${#arr_dir[@]}" -ge "${int_max_count}" ]]; then
-    #             echo "deleted file"
-    #             DeleteFile "${arr_dir[0]}" || return $?
-    #         fi
+            IsFile $1 || return $?
 
-    #         # <remarks> Get index of newest backup file. </remarks>
-    #         local str_oldest_file="${arr_dir[-1]}"
-    #         str_oldest_file="${str_oldest_file%%"${str_suffix}"*}"
-    #         str_index="${str_oldest_file##*.}"
-    #         IsNum "$str_index" && int_index="${str_index}" || int_index=1
-    #         (( int_index++ ))
-    #         echo $int_index
-    #         eval "${var_pad_zeros}"
+            # <params>
+            declare -ir int_max_count=3
+            local readonly str_suffix=".old"
+            local readonly var_get_backups='ls -t '"${str_dir}"' | grep '$1' | grep -i '"${str_suffix}"' | uniq'
+            declare -a arr_dir=( $( eval "${var_get_backups}" ) )
+            declare -i int_index=1
+            # </params>
 
-    #         # <remarks> Create backup. </remarks>
-    #         cp $1 "${1}.${str_index}${str_suffix}" || return 1
+            # <remarks> If none exist, create backup. </remarks>
+            if ! IsArray arr_dir; then
+                str_index=$( BackupFile_GetNum "${str_index}" )
+                cp $1 "${1}.${str_index}${str_suffix}" || return 1
+            fi
 
-    #         return 0
-    #     }
+            # <remarks> If newest backup is same as file, exit. </remarks>
+            if AreEqualFiles $1 "${arr_dir[0]}"; then
+                return "${int_code_skipped_operation}"
+            fi
 
-    #     # <params>
-    #     local readonly str_output="Creating backup file..."
-    #     # </params>
+            # <remarks> If amount of backups exceeds maximum, delete oldest backup. </remarks>
+            if [[ "${#arr_dir[@]}" -ge "${int_max_count}" ]]; then
+                DeleteFile "${arr_dir[-1]}" || return $?
+            fi
 
-    #     echo -e "${str_output}"
-    #     BackupFile_Main $1
-    #     PrintPassOrFail "${str_output}"
-    #     return "${int_exit_code}"
-    # }
+            # <remarks> Create backup. </remarks>
+            str_index=$( BackupFile_GetNum "${str_index}" )
+            cp $1 "${1}.${str_index}${str_suffix}" || return 1
+
+            return 0
+        }
+
+        # <params>
+        local readonly str_output="Creating backup file..."
+        # </params>
+
+        echo -e "${str_output}"
+        BackupFile_Main $1
+        PrintPassOrFail "${str_output}"
+        return "${int_exit_code}"
+    }
 
     # <summary> Create a directory. </summary>
     # <param name=$1> string: the directory </param>
